# Generated by Django 3.0.8 on 2020-08-04 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artistas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.CharField(max_length=250)),
                ('biografia', models.CharField(max_length=250)),
                ('nombre', models.CharField(max_length=100)),
                ('num_canciones', models.IntegerField(verbose_name=10)),
                ('estado', models.CharField(max_length=30)),
            ],
        ),
    ]
