# Generated by Django 3.0.8 on 2020-08-04 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_canciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canciones',
            name='autor',
            field=models.CharField(default='', max_length=10),
        ),
    ]
