# Generated by Django 3.0.8 on 2020-08-06 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20200804_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artistas',
            name='biografia',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='artistas',
            name='estado',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
